version: "3"
services:
  db:
    image: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 9hzMAYRGgZ8trxWkF
      MYSQL_DATABASE: spicaring

  spicaprofilering:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_NAME: spicaring
      DB_USERNAME: root
      DB_PASSWORD: 9hzMAYRGgZ8trxWkF
      DB_HOST: db

    depends_on:
      - db
    links:
      - db
