name: Deploy to CapRover

on:
  push:
    branches: [ main ]
    
defaults:
  run:
    working-directory: ./
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CapRover Deploy
        run: |
          sudo chown -R $USER /usr/local/lib/node_modules
          npm install -g caprover
          caprover deploy -h 'https://captain.main01.abmgrt.dev' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'main' -a 'spicaring'
#        uses: AlexxNB/caprover-action@v1
#        with:
#          server: 'https://captain.main01.abmgrt.dev'
#          password: '${{ secrets.CAPROVER_PASSWORD }}'
#          appname: 'spicaring'
#          branch: main
