name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Install CapRover CLI
        working-directory: ./
        run: |
          npm install caprover
          caprover deploy -h 'https://captain.main01.abmgrt.dev' -p ${{ secrets.CAPROVER_PASSWORD }} -b main -a spicaring 
     #   uses: AlexxNB/caprover-action@v1
    #    with:
   #       server: 'https://captain.main01.abmgrt.dev'
  #        password: '${{ secrets.CAPROVER_PASSWORD }}'
 #         appname: 'spicaring'
#          branch: main
