name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CapRover Deploy
        uses: AlexxNB/caprover-action@v1
        with:
          server: 'https://captain.main01.abmgrt.dev'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'spicaring'
          branch: main
